version: 1
default_severity: warning

rules:
  - name: "Changelog Check"
    condition: "require-changelog"
    
    # We are looking for the exact word "TODO"
    # terms: ["TODO"]
    # caseSensitive: true
    # This rule will be a hard failure
    severity: error
