version: 1
default_severity: warning

rules:
  - name: "Tests Required for Source Changesk"
    condition: "require-testsg"
    # This rule will be a hard failure
    severity: error
    testPatterns: 
      - "**/*.test.js"
      - "**/*.spec.js"
