version: 1
default_severity: warning

rag_sources:
  # High-priority architectural decision records
  - path: "docs/adr/**/*.md"
    weight: 0.9

  # General development guidelines
  - path: "docs/guides/**/*.md" # Note: This path is intentionally wrong for a later test
    weight: 0.5

  # The main README is also a source of context
  - path: "README.md"
    weight: 0.2
rules:
  - name: "AI Database Policy Check"
    condition: "ai-review"
    # The severity 'error' means if the AI finds a violation, it should block the merge.
    severity: "error"
    # This is the exact question we are asking the AI.
    prompt: "A developer is adding a new service and wants to use MongoDB database. Based on our team's documentation, is this allowed?" 