version: 1
default_severity: warning

rag_sources:
  # High-priority architectural decision records
  - path: "docs/adr/**/*.md"
    weight: 0.9

  # General development guidelines
  - path: "docs/guides/**/*.md" # Note: This path is intentionally wrong for a later test
    weight: 0.3

  # The main README is also a source of context
  - path: "README.md"
    weight: 0.2
rules:
  - name: "AI Database Policy Check"
    condition: "ai-review"
    # The severity 'error' means if the AI finds a violation, it should block the merge.
    severity: "warning"
    # This is the exact question we are asking the AI.
    prompt: "A new developer on the team is asking about our testing and database standards. Please provide a summary of our key requirements based on the documentation." 