version: 1
default_severity: warning

rules:
  - name: "AI Security Check: Authorization"
    condition: "ai-review"
    severity: warning
    prompt: "Based on our best practices documentation, does the new API endpoint in this diff correctly perform an authorization check before fetching data? The code should check the user's identity."