version: 1
default_severity: warning

rag_sources:
  # High-priority architectural decision records
  - path: "docs/adr/**/*.md"
    weight: 0.9

  # General development guidelines
  - path: "docs/guides/development.md" # Note: This path is intentionally wrong for a later test
    weight: 0.7

  # The main README is also a source of context
  - path: "README.md"
    weight: 0.5
rules: [] # No rules needed for this test