version: 1
default_severity: warning

rag_sources:
  # High-priority architectural decision records
  - path: "docs/adr/**/*.md"
    weight: 0.9

  # General development guidelines
  - path: "docs/guides/**/*.md" # Note: This path is intentionally wrong for a later test
    weight: 0.3

  # The main README is also a source of context
  - path: "README.md"
    weight: 0.2
rules:
  - name: "AI Database Policy Check"
    condition: "policy-question" 
    severity: "error"
    prompt: "A developer is adding a new service and wants to use MongoDB. Based on our team's documentation, is this allowed?"